from django.contrib import admin
from django.urls import path
from homepage.views import HomepageView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomepageView.as_view(), name='view'),
]

# HomepageView.as_view() creates a callable object, this callable object is analogous to a function. Django calls
# this object by passing in an HttpRequest generated by the user and then the object returns a HttpResponse. Django
# supplies the HttpResponse back to the user.
